#!/bin/sh
set -e

make format
make lint

# Re-add files that are currently staged to include any changes made by format/lint
git diff --name-only --cached --diff-filter=ACMR -z | xargs -0 --no-run-if-empty git add
