[workspace]
members = [
  "crates/keymap-core",
  "crates/keymap-overlay",
  "crates/keymap-overlay-windows-bridge",
]
exclude = ["crates/keymap-overlay-qt-bridge"]
resolver = "2"

[workspace.package]
version = "0.0.3"
license = "MIT"
repository = "https://github.com/sunaemon/keymap-overlay"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
cognitive_complexity = "warn"
