from typing import Any

def enumerate(vendor_id: int = 0, product_id: int = 0) -> list[dict[str, Any]]: ...

class device:
    def __init__(self) -> None: ...
    def open(
        self, vendor_id: int, product_id: int, serial_number: str | None = None
    ) -> None: ...
    def open_path(self, path: bytes) -> None: ...
    def close(self) -> None: ...
    def write(self, data: bytes) -> int: ...
    def read(self, max_length: int, timeout_ms: int = 0) -> list[int]: ...
    def get_manufacturer_string(self) -> str | None: ...
    def get_product_string(self) -> str | None: ...
    def get_serial_number_string(self) -> str | None: ...
    def get_feature_report(self, report_id: int, max_length: int) -> list[int]: ...
    def send_feature_report(self, data: bytes) -> int: ...
    def set_nonblocking(self, nonblock: int) -> int: ...
    def error(self) -> str: ...

class Device:
    def __init__(
        self,
        path: bytes | None = None,
        vid: int | None = None,
        pid: int | None = None,
        serial: str | None = None,
    ) -> None: ...
    def close(self) -> None: ...
    def write(self, data: bytes) -> int: ...
    def read(self, size: int, timeout: int | None = None) -> bytes: ...
    @property
    def nonblocking(self) -> bool: ...
    @nonblocking.setter
    def nonblocking(self, value: bool) -> None: ...
